f = open("简单的问题.in", "r")
f1 = open("简单的问题.out", "w")
m1=float(f.readline())
print(m1)
print("%.2f"%m1)
m2=float(f.readline())
print(m2)
print("%.2f"%m2)
s=float(m1)+float(m2)
print("%.2f"%s)
f1.write(str(s))
